### ISSUE TITLE
winesync-dkms 5.16-5 does not build with CachyOS Kernel version 6.12.7-2

### ISSUE THREAD

**Issue by RubenKelevra** [CachyOS/linux-cachyos#370]
I got an error after updating a system after a month or so:

```
(13/34) Install DKMS modules
==> dkms install --no-depmod winesync/5.16 -k 6.6.68-1-cachyos-lts-lto
==> dkms install --no-depmod binder/1 -k 6.12.7-2-cachyos
==> dkms install --no-depmod winesync/5.16 -k 6.12.7-2-cachyos

Error! Bad return status for module build on kernel: 6.12.7-2-cachyos (x86_64)
Consult /var/lib/dkms/winesync/5.16/build/make.log for more information.
==> WARNING: `dkms install --no-depmod winesync/5.16 -k 6.12.7-2-cachyos' exited 10
```  

```  
❯ cat /var/lib/dkms/winesync/5.16/build/make.log
DKMS make.log for winesync/5.16 for kernel 6.12.7-2-cachyos (x86_64)
Fri Jan  3 01:01:36 AM CET 2025
make: Entering directory '/usr/lib/modules/6.12.7-2-cachyos/build'
  CC [M]  /var/lib/dkms/winesync/5.16/build/src/drivers/misc/winesync.o
/var/lib/dkms/winesync/5.16/build/src/drivers/misc/winesync.c:1186:13: error: use of undeclared identifier 'no_llseek'; did you mean 'noop_llseek'?
 1186 |         .llseek         = no_llseek,
      |                           ^~~~~~~~~
      |                           noop_llseek
./include/linux/fs.h:3241:15: note: 'noop_llseek' declared here
 3241 | extern loff_t noop_llseek(struct file *file, loff_t offset, int whence);
      |               ^
1 error generated.
make[2]: *** [scripts/Makefile.build:229: /var/lib/dkms/winesync/5.16/build/src/drivers/misc/winesync.o] Error 1
make[1]: *** [/usr/lib/modules/6.12.7-2-cachyos/build/Makefile:1947: /var/lib/dkms/winesync/5.16/build] Error 2
make: *** [Makefile:224: __sub-make] Error 2
make: Leaving directory '/usr/lib/modules/6.12.7-2-cachyos/build'

```

**Comment by ptr1337** [comment]
winesync is no longer maintained nor used. You should remove this package
