### ISSUE TITLE
[BUG] dkms wasn't able to install broadcom-wl/6.30.223.271 to 7.1.1-2-cachyos

### ISSUE THREAD

**Issue by nguyendoan15082006** [CachyOS/linux-cachyos#893]
### Pre-flight checklist

- [x] I have searched existing issues and this is not a duplicate.
- [x] I have read the [Contributing Guidelines](https://github.com/CachyOS/linux-cachyos/blob/master/CONTRIBUTING.md).
- [x] I have verified the issue is reproducible with the latest available CachyOS kernel.
- [x] I have tried to reproduce the issue on Arch Linux's `linux` kernel.

### Upstream / vanilla kernel check

I have not tested with a vanilla/upstream kernel

### Kernel variant

linux-cachyos (EEVDF, Clang)

### System information (cachyos-bugreport.sh)

```text
Kernel: 6.18.36-1-cachyos-lts arch: x86_64 bits: 64 compiler: clang
    v: 22.1.6 clocksource: tsc avail: acpi_pm
    parameters: BOOT_IMAGE=/vmlinuz-linux-cachyos-lts
    root=UUID=bcbe881e-bd8c-458e-9bf8-135b040fa848 rw rootflags=subvol=@
    root=UUID=bcbe881e-bd8c-458e-9bf8-135b040fa848 rw rootflags=subvol=/@
    zswap.enabled=0 nowatchdog plymouth.enable=0 disablehooks=plymouth
    mitigations=off loglevel=7
  Desktop: KDE Plasma v: 6.7.1 tk: Qt v: N/A wm: kwin_wayland dm: N/A
    Distro: CachyOS base: Arch Linux
Machine:
  Type: Portable System: Dell product: Inspiron 3543 v: A13 serial: <filter>
    Chassis: type: 8 serial: <filter>
  Mobo: Dell model: 0M9V4C v: A00 serial: <filter> part-nu: 0654
    uuid: 4c4c4544-0038-4710-804d-b4c04f443332 Firmware: UEFI vendor: Dell
    v: A13 date: 09/02/2020
CPU:
  Info: model: Intel Core i5-5200U socket: BGA1168 bits: 64 type: MT MCP
    arch: Broadwell gen: core 5 level: v3 note: check built: 2015-18
    process: Intel 14nm family: 6 model-id: 0x3D (61) stepping: 4
    microcode: 0x2F
  Topology: cpus: 1x dies: 1 clusters: 2 cores: 2 threads: 4 tpc: 2
    smt: enabled cache: L1: 128 KiB desc: d-2x32 KiB; i-2x32 KiB L2: 512 KiB
    desc: 2x256 KiB L3: 3 MiB desc: 1x3 MiB
  Speed (MHz): avg: 500 min/max: 500/2700 base/boost: 2500/2200 scaling:
    driver: intel_cpufreq governor: schedutil volts: 1.0 V ext-clock: 100 MHz
    cores: 1: 500 2: 500 3: 500 4: 500 bogomips: 17560
  Flags-basic: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
  Vulnerabilities:
  Type: gather_data_sampling status: Not affected
  Type: ghostwrite status: Not affected
  Type: indirect_target_selection status: Not affected
  Type: itlb_multihit status: KVM: Vulnerable
  Type: l1tf mitigation: PTE Inversion; VMX: vulnerable
  Type: mds status: Vulnerable; SMT vulnerable
  Type: meltdown status: Vulnerable
  Type: mmio_stale_data status: Not affected
  Type: old_microcode status: Not affected
  Type: reg_file_data_sampling status: Not affected
  Type: retbleed status: Not affected
  Type: spec_rstack_overflow status: Not affected
  Type: spec_store_bypass status: Vulnerable
  Type: spectre_v1 status: Vulnerable: __user pointer sanitization and
    usercopy barriers only; no swapgs barriers
  Type: spectre_v2 status: Vulnerable; IBPB: disabled; STIBP: disabled;
    PBRSB-eIBRS: Not affected; BHI: Not affected
  Type: srbds status: Vulnerable
  Type: tsa status: Not affected
  Type: tsx_async_abort status: Not affected
  Type: vmscape status: Vulnerable
Graphics:
  Device-1: Intel Broadwell-U GT2 [HD Graphics 5500] vendor: Dell driver: i915
    v: kernel arch: Gen-8 process: Intel 14nm built: 2014-15 ports:
    active: eDP-1 empty: HDMI-A-1 bus-ID: 00:02.0 chip-ID: 8086:1616
    class-ID: 0300
  Device-2: Sunplus Innovation Integrated_Webcam_HD driver: uvcvideo
    type: USB rev: 2.0 speed: 480 Mb/s lanes: 1 mode: 2.0 bus-ID: 1-1.5:4
    chip-ID: 1bcf:2b8b class-ID: 0e02
  Display: unspecified server: X.Org v: 24.1.12 with: Xwayland v: 24.1.12
    compositor: kwin_wayland driver: gpu: i915 display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1366x768 s-dpi: 96 s-size: 361x203mm (14.21x7.99")
    s-diag: 414mm (16.31")
  Monitor-1: eDP-1 model: BOE Display 0x0615 built: 2014 res: mode: 1366x768
    hz: 60 scale: 100% (1) dpi: 112 gamma: 1.2 size: 309x173mm (12.17x6.81")
    diag: 389mm (15.3") ratio: 16:9, 15:9 modes: 1366x768
  API: EGL v: 1.5 hw: drv: intel iris platforms: device: 0 drv: iris
    device: 1 drv: swrast gbm: drv: iris surfaceless: drv: iris x11: drv: iris
    inactive: wayland
  API: OpenGL v: 4.6 vendor: intel mesa v: 26.1.2-arch3.1 glx-v: 1.4
    direct-render: yes renderer: Mesa Intel HD Graphics 5500 (BDW GT2)
    device-ID: 8086:1616 memory: 7.48 GiB unified: yes
  API: Vulkan v: 1.4.350 layers: 5 device: 0 type: integrated-gpu name: Intel
    HD Graphics 5500 (BDW GT2) driver: mesa intel v: 26.1.2-arch3.1
    device-ID: 8086:1616 surfaces: N/A
  Info: Tools: api: clinfo, eglinfo, glxinfo, vulkaninfo
    de: kscreen-console,kscreen-doctor wl: wayland-info
    x11: xdpyinfo, xprop, xrandr
Audio:
  Device-1: Intel Broadwell-U Audio vendor: Dell driver: snd_hda_intel
    v: kernel bus-ID: 00:03.0 chip-ID: 8086:160c class-ID: 0403
  Device-2: Intel Wildcat Point-LP High Definition Audio vendor: Dell
    driver: snd_hda_intel v: kernel bus-ID: 00:1b.0 chip-ID: 8086:9ca0
    class-ID: 0403
  API: ALSA v: k6.18.36-1-cachyos-lts status: kernel-api
    tools: alsactl,alsamixer,amixer
  Server-1: sndiod v: N/A status: off tools: aucat,midicat,sndioctl
  Server-2: JACK v: 0.126.0 status: off tools: N/A
  Server-3: PipeWire v: 1.6.7 status: n/a (root, process) with:
    1: pipewire-pulse status: active 2: wireplumber status: active
    3: pipewire-alsa type: plugin tools: pactl,pw-cat,pw-cli,wpctl
Network:
  Device-1: Broadcom BCM43142 802.11b/g/n vendor: Dell Wireless 1704 802.11n
    + BT 4.0 driver: wl v: kernel modules: bcma pcie: gen: 1 speed: 2.5 GT/s
    lanes: 1 bus-ID: 06:00.0 chip-ID: 14e4:4365 class-ID: 0280
  IF: wlan0 state: up mac: <filter>
  Device-2: Realtek RTL810xE PCI Express Fast Ethernet vendor: Dell
    driver: r8169 v: kernel pcie: gen: 1 speed: 2.5 GT/s lanes: 1 port: 3000
    bus-ID: 07:00.0 chip-ID: 10ec:8136 class-ID: 0200
  IF: enp7s0 state: down mac: <filter>
  IF-ID-1: virbr0 state: down mac: <filter>
  Info: services: NetworkManager, smbd, systemd-timesyncd, wpa_supplicant
Bluetooth:
  Device-1: Broadcom BCM43142 Bluetooth 4.0 driver: btusb v: 0.8 type: USB
    rev: 2.0 speed: 12 Mb/s lanes: 1 mode: 1.1 bus-ID: 1-1.6:5
    chip-ID: 0a5c:21d7 class-ID: fe01 serial: <filter>
  Report: btmgmt ID: hci0 rfk-id: 1 state: down bt-service: enabled,running
    rfk-block: hardware: no software: yes address: <filter> bt-v: 4.0 lmp-v: 6
    status: discoverable: no pairing: yes
Drives:
  Local Storage: total: 223.57 GiB used: 84.18 GiB (37.7%)
  ID-1: /dev/sda maj-min: 8:0 vendor: Kingston model: SUV400S37240G
    family: SSDNow UV400/500 size: 223.57 GiB block-size: physical: 4096 B
    logical: 512 B sata: 3.1 speed: 6.0 Gb/s tech: SSD serial: <filter>
    fw-rev: 96R9 temp: 38 C scheme: GPT
  SMART: yes state: enabled health: PASSED on: 2y 224d 6h cycles: 17908
Partition:
  ID-1: / raw-size: 93.31 GiB size: 93.31 GiB (100.00%) used: 62.2 GiB (66.7%)
    fs: btrfs block-size: 4096 B dev: /dev/sda7 maj-min: 8:7
  ID-2: /boot raw-size: 2 GiB size: 2 GiB (99.80%) used: 203 MiB (9.9%)
    fs: vfat block-size: 512 B dev: /dev/sda6 maj-min: 8:6
  ID-3: /home raw-size: 93.31 GiB size: 93.31 GiB (100.00%)
    used: 62.2 GiB (66.7%) fs: btrfs block-size: 4096 B dev: /dev/sda7
    maj-min: 8:7
  ID-4: /var/log raw-size: 93.31 GiB size: 93.31 GiB (100.00%)
    used: 62.2 GiB (66.7%) fs: btrfs block-size: 4096 B dev: /dev/sda7
    maj-min: 8:7
  ID-5: /var/tmp raw-size: 93.31 GiB size: 93.31 GiB (100.00%)
    used: 62.2 GiB (66.7%) fs: btrfs block-size: 4096 B dev: /dev/sda7
    maj-min: 8:7
Swap:
  Kernel: swappiness: 150 (default 60) cache-pressure: 50 (default 100)
    zswap: no
  ID-1: swap-1 type: zram size: 7.66 GiB used: 4.7 MiB (0.1%) priority: 100
    comp: zstd avail: lzo-rle,lzo,lz4,lz4hc,deflate,842 dev: /dev/zram0
Sensors:
  System Temperatures: cpu: 52.0 C mobo: 53.0 C
  Fan Speeds (rpm): cpu: 0
Repos:
  Packages: 1634 pm: pacman pkgs: 1625 libs: 383 tools: paru,yay pm: flatpak
    pkgs: 9
  Active pacman repo servers in: /etc/pacman.d/cachyos-mirrorlist
    1: https://mirror.krfoss.org/cachyos/repo/$arch/$repo
    2: https://cdn77.cachyos.org/repo/$arch/$repo
    3: https://mirror5.krfoss.org/cachyos/repo/$arch/$repo
    4: https://mirror.mergedcloud.de/cachyos/repo/$arch/$repo
    5: https://mirror2.keiminem.com/cachyos/repo/$arch/$repo
    6: https://us-mnz.soulharsh007.dev/cachyos/repo/$arch/$repo
    7: https://mirror.keiminem.com/cachyos/repo/$arch/$repo
    8: https://mirrors.ustc.edu.cn/cachyos/repo/$arch/$repo
    9: https://mirror.zyner.org/mirror/cachyos/repo/$arch/$repo
    10: https://ca.mirror.cx/cachyos/repo/$arch/$repo
    11: https://mirror.hb9hil.org/cachyos/repo/$arch/$repo
    12: https://us.cachyos.org/repo/$arch/$repo
    13: https://mirror.cachy-arch.ru/cachyos/repo/$arch/$repo
    14: https://nl.mirror.cx/cachyos/repo/$arch/$repo
    15: https://cdn.lansing2600.org/cachyos/repo/$arch/$repo
    16: https://cachyos-mirror.m1k.cloud/repo/$arch/$repo
    17: https://at.cachyos.org/repo/$arch/$repo
    18: https://mirror.nju.edu.cn/cachyos/repo/$arch/$repo
    19: https://mirror.lesviallon.fr/cachy/repo/$arch/$repo
    20: https://no.mirror.cx/cachyos/repo/$arch/$repo
    21: https://mirrors.lansing2600.org/cachyos/repo/$arch/$repo
    22: https://mirror.jura12.ru/repo/$arch/$repo
    23: https://cachyos.next-works.it/repo/$arch/$repo
    24: https://cachyos.doridian.net/repo/$arch/$repo
  Active pacman repo servers in: /etc/pacman.d/cachyos-v3-mirrorlist
    1: https://mirror.krfoss.org/cachyos/repo/$arch_v3/$repo
    2: https://cdn77.cachyos.org/repo/$arch_v3/$repo
    3: https://mirror5.krfoss.org/cachyos/repo/$arch_v3/$repo
    4: https://mirror.mergedcloud.de/cachyos/repo/$arch_v3/$repo
    5: https://mirror2.keiminem.com/cachyos/repo/$arch_v3/$repo
    6: https://us-mnz.soulharsh007.dev/cachyos/repo/$arch_v3/$repo
    7: https://mirror.keiminem.com/cachyos/repo/$arch_v3/$repo
    8: https://mirrors.ustc.edu.cn/cachyos/repo/$arch_v3/$repo
    9: https://mirror.zyner.org/mirror/cachyos/repo/$arch_v3/$repo
    10: https://ca.mirror.cx/cachyos/repo/$arch_v3/$repo
    11: https://mirror.hb9hil.org/cachyos/repo/$arch_v3/$repo
    12: https://us.cachyos.org/repo/$arch_v3/$repo
    13: https://mirror.cachy-arch.ru/cachyos/repo/$arch_v3/$repo
    14: https://nl.mirror.cx/cachyos/repo/$arch_v3/$repo
    15: https://cdn.lansing2600.org/cachyos/repo/$arch_v3/$repo
    16: https://cachyos-mirror.m1k.cloud/repo/$arch_v3/$repo
    17: https://at.cachyos.org/repo/$arch_v3/$repo
    18: https://mirror.nju.edu.cn/cachyos/repo/$arch_v3/$repo
    19: https://mirror.lesviallon.fr/cachy/repo/$arch_v3/$repo
    20: https://no.mirror.cx/cachyos/repo/$arch_v3/$repo
    21: https://mirrors.lansing2600.org/cachyos/repo/$arch_v3/$repo
    22: https://mirror.jura12.ru/repo/$arch_v3/$repo
    23: https://cachyos.next-works.it/repo/$arch_v3/$repo
    24: https://cachyos.doridian.net/repo/$arch_v3/$repo
  Active pacman repo servers in: /etc/pacman.d/mirrorlist
    1: https://archlinux.cachyos.org/repo/$repo/os/$arch
    2: https://mirrors.huong<username-redacted>.dev/arch/$repo/os/$arch
    3: https://mirror.krfoss.org/archlinux/$repo/os/$arch
    4: https://mirror.osbeck.com/archlinux/$repo/os/$arch
    5: https://fastly.mirror.pkgbuild.com/$repo/os/$arch
    6: https://mirror.twds.com.tw/archlinux/$repo/os/$arch
    7: https://mirror.xtom.com.hk/archlinux/$repo/os/$arch
    8: https://geo.mirror.pkgbuild.com/$repo/os/$arch
    9: https://arch.yhtez.xyz/$repo/os/$arch
    10: https://mirrors.aliyun.com/archlinux/$repo/os/$arch
    11: https://ftp.energotel.sk/pub/linux/arch/$repo/os/$arch
    12: https://archlinux.ip-connect.vn.ua/$repo/os/$arch
    13: https://arch.midov.pl/arch/$repo/os/$arch
    14: https://mirrors.pidginhost.com/arch/$repo/os/$arch
    15: https://theswissbay.ch/archlinux/$repo/os/$arch
    16: https://singapore.mirror.pkgbuild.com/$repo/os/$arch
    17: https://london.mirror.pkgbuild.com/$repo/os/$arch
    18: https://mirrors.xtom.ee/archlinux/$repo/os/$arch
    19: https://taipei.mirror.pkgbuild.com/$repo/os/$arch
    20: https://hu.mirror.frigyes.dev/archlinux/$repo/os/$arch
    21: https://at.arch.niranjan.co/$repo/os/$arch
    22: https://no.mirror.cx/archlinux/$repo/os/$arch
    23: https://uk.repo.c48.uk/arch/$repo/os/$arch
    24: https://ftp.linux.edu.lv/archlinux/$repo/os/$arch
    25: https://ftp.sh.cvut.cz/arch/$repo/os/$arch
    26: https://mirror.group.one/archlinux/$repo/os/$arch
    27: https://mirror.neuf.no/archlinux/$repo/os/$arch
    28: https://mirror.raiolanetworks.com/archlinux/$repo/os/$arch
    29: https://berlin.mirror.pkgbuild.com/$repo/os/$arch
    30: https://at.arch.mirror.kescher.at/$repo/os/$arch
    31: https://www.miraa.jp/archlinux/$repo/os/$arch
    32: https://repo.br.ee/arch/$repo/os/$arch
    33: https://mirror.juniorjpdj.pl/archlinux/$repo/os/$arch
    34: https://arlm.tyzoid.com/$repo/os/$arch
    35: https://mirror.1ago.be/archlinux/$repo/os/$arch
    36: https://mirror.lcarilla.de/archlinux/$repo/os/$arch
    37: https://mirror.lu.stratonexus.net/archlinux/$repo/os/$arch
    38: https://archlinux.mailtunnel.eu/$repo/os/$arch
    39: https://umea.mirror.pkgbuild.com/$repo/os/$arch
    40: https://mirror.nw-sys.ru/archlinux/$repo/os/$arch
    41: https://mirrors.nxthost.com/archlinux/$repo/os/$arch
    42: https://mirror.trapmaid.org/archlinux/$repo/os/$arch
    43: https://ftpmirror.infania.net/mirror/archlinux/$repo/os/$arch
    44: https://arch.mirror.constant.com/$repo/os/$arch
    45: https://mirrors.jlu.edu.cn/archlinux/$repo/os/$arch
    46: https://mirror.archlinux.si/$repo/os/$arch
Info:
  Memory: total: 8 GiB available: 7.66 GiB used: 2.83 GiB (36.9%) igpu: 32 MiB
  Processes: 254 Power: uptime: 11m states: freeze,mem,disk suspend: deep
    avail: s2idle wakeups: 0 hibernate: platform avail: shutdown, reboot,
    suspend, test_resume image: 3.01 GiB services: org_kde_powerdevil,
    power-profiles-daemon, upowerd Init: systemd v: 260 default: graphical
    tool: systemctl
  Compilers: clang: 22.1.6 gcc: 16.1.1 Shell: Bash (sudo) v: 5.3.9
    running-in: konsole inxi: 3.3.40
```

### Manual system information (if cachyos-bugreport.sh is unavailable)

```text

```

### Bug description

When updating the system to kernel `linux-cachyos 7.1.1-2`, the` broadcom-wl` module fails to compile via DKMS using Clang/LLVM (LLVM=1). The build process exits with a bad status (exit status: 2) due to incompatible function pointer types in the cfg80211 subsystem, rendering the Broadcom Wi-Fi card completely non-functional on the new kernel.

The main compilation failure from make.log points to an API mismatch where the driver still uses `struct net_device *dev `instead of the expected struct `wireless_dev *wdev `required by Kernel 7.1:
```
src/wl/sys/wl_cfg80211_hybrid.c:1845:17: error: incompatible function pointer types initializing 'int (*)(struct wiphy *, struct wireless_dev *, const u8 *, struct station_info *)' ... with an expression of type 's32 (struct wiphy *, struct net_device *, const u8 *, struct station_info *)'
 1845 |         .get_station = wl_cfg80211_get_station,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~
```
Note: This error also affects .add_key, .del_key, and .get_key hooks within wl_cfg80211_hybrid.c
`cat /var/lib/dkms/broadcom-wl/6.30.223.271/build/make.log | grep -A 3 -B 1 "error:"` output:
```
      |                           ^
src/wl/sys/wl_cfg80211_hybrid.c:1845:17: error: incompatible function pointer types initializing 'int (*)(struct wiphy *, struct wireless_dev *, const u8 *, struct station_info *)' (aka 'int (*)(struct wiphy *, struct wireless_dev *, const unsigned char *, struct station_info *)') with an expression of type 's32 (struct wiphy *, struct net_device *, const u8 *, struct station_info *)' (aka 'int (struct wiphy *, struct net_device *, const unsigned char *, struct station_info *)') [-Wincompatible-function-pointer-types]
 1845 |         .get_station = wl_cfg80211_get_station,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~
src/wl/sys/wl_cfg80211_hybrid.c:1848:13: error: incompatible function pointer types initializing 'int (*)(struct wiphy *, struct wireless_dev *, int, u8, bool, const u8 *, struct key_params *)' (aka 'int (*)(struct wiphy *, struct wireless_dev *, int, unsigned char, _Bool, const unsigned char *, struct key_params *)') with an expression of type 's32 (struct wiphy *, struct net_device *, int, u8, bool, const u8 *, struct key_params *)' (aka 'int (struct wiphy *, struct net_device *, int, unsigned char, _Bool, const unsigned char *, struct key_params *)') [-Wincompatible-function-pointer-types]
 1848 |         .add_key = wl_cfg80211_add_key,
      |                    ^~~~~~~~~~~~~~~~~~~
src/wl/sys/wl_cfg80211_hybrid.c:1849:13: error: incompatible function pointer types initializing 'int (*)(struct wiphy *, struct wireless_dev *, int, u8, bool, const u8 *)' (aka 'int (*)(struct wiphy *, struct wireless_dev *, int, unsigned char, _Bool, const unsigned char *)') with an expression of type 's32 (struct wiphy *, struct net_device *, int, u8, bool, const u8 *)' (aka 'int (struct wiphy *, struct net_device *, int, unsigned char, _Bool, const unsigned char *)') [-Wincompatible-function-pointer-types]
 1849 |         .del_key = wl_cfg80211_del_key,
      |                    ^~~~~~~~~~~~~~~~~~~
src/wl/sys/wl_cfg80211_hybrid.c:1850:13: error: incompatible function pointer types initializing 'int (*)(struct wiphy *, struct wireless_dev *, int, u8, bool, const u8 *, void *, void (*)(void *, struct key_params *))' (aka 'int (*)(struct wiphy *, struct wireless_dev *, int, unsigned char, _Bool, const unsigned char *, void *, void (*)(void *, struct key_params *))') with an expression of type 's32 (struct wiphy *, struct net_device *, int, u8, bool, const u8 *, void *, void (*)(void *, struct key_params *))' (aka 'int (struct wiphy *, struct net_device *, int, unsigned char, _Bool, const unsigned char *, void *, void (*)(void *, struct key_params *))') [-Wincompatible-function-pointer-types]
 1850 |         .get_key = wl_cfg80211_get_key,
      |                    ^~~~~~~~~~~~~~~~~~~
src/wl/sys/wl_linux.c:553:36: warning: cast from 'void (*)(wl_task_t *)' (aka 'void (*)(struct wl_task *)') to 'work_func_t' (aka 'void (*)(struct work_struct *)') converts to incompatible function type [-Wcast-function-type-strict]
```

DKMS Terminal Output:
```
Sign command: /usr/lib/modules/7.1.1-2-cachyos/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module(s)....(bad exit status: 2)
Failed command:
make -j4 KERNELRELEASE=7.1.1-2-cachyos -C /usr/lib/modules/7.1.1-2-cachyos/build M=/var/lib/dkms/broadcom-wl/6.30.223.271/build LLVM=1

Error! Bad return status for module build on kernel: 7.1.1-2-cachyos (x86_64)
Consult /var/lib/dkms/broadcom-wl/6.30.223.271/build/make.log for more information.
```

### Steps to reproduce

1. Launch the Cachy-Update application (or run sudo pacman -Syu) to update the system.
2. Allow the system to update the kernel to linux-cachyos 7.1.1-2.
3. Observe the DKMS compilation error for broadcom-wl (6.30.223.271) during the hook phase.
4. Restart the computer and boot into Kernel 7.1.1-2.

### Expected behavior

The `broadcom-wl` driver should be successfully compiled by DKMS without any compilation errors on Kernel 7.1.1-2, and the Wi-Fi interface should initialize and function normally after rebooting.

### Actual behavior

Wi-Fi is completely unavailable. The workaround is booting into kernel `6.18.36` and the Broadcom wifi driver works completely fine.
**Note on Arch Linux's kernel check**: I ticked the checkbox because it is a required field to submit the issue. However, I am unable to actually test this on the stock Arch kernel because upstream Arch is still on kernel 7.0.12, while this DKMS failure is strictly triggered by the new API changes in Kernel 7.1+.

### Logs / stack traces

```text

```

**Comment by ptr1337** [comment]
Can you try with this patch? 

[022-linux71.patch](https://github.com/user-attachments/files/29308060/022-linux71.patch)

**Comment by ptr1337** [comment]
You can also do

sudo pacman -U https://build.cachyos.org/repo/x86_64/cachyos/broadcom-wl-dkms-6.30.223.271-49-x86_64.pkg.tar.zst

**Comment by nguyendoan15082006** [comment]
> You can also do
> 
> sudo pacman -U https://build.cachyos.org/repo/x86_64/cachyos/broadcom-wl-dkms-6.30.223.271-49-x86_64.pkg.tar.zst

Thanks you,Peter. Now my broadcom-wl worked fine.

<img width="1366" height="768" alt="Image" src="https://github.com/user-attachments/assets/bd2fb012-ee98-49da-9984-d98b7f8a656e" />

**Comment by Soterlll** [comment]
I had a simillar problem today. it seems you need 6.30.223.271-49 version which is only present in cachyos repo, not in v3,v4 etc.  this command helped to install it: sudo pacman -S cachyos/broadcom-wl-dkms. i guess the new version of the package should get updated in other repos
