### ISSUE TITLE
[BUG] Realtek 0bda:c811 (Cudy AC650/WU650) does not work on linux-cachyos 7.1.3-2 but works on linux-cachyos-lts 6.18

### ISSUE THREAD

**Issue by Benicio54** [CachyOS/linux-cachyos#923]
### Pre-flight checklist

- [x] I have searched existing issues and this is not a duplicate.
- [x] I have read the [Contributing Guidelines](https://github.com/CachyOS/linux-cachyos/blob/master/CONTRIBUTING.md).
- [x] I have verified the issue is reproducible with the latest available CachyOS kernel.
- [x] I have tried to reproduce the issue on Arch Linux's `linux` kernel.

### Upstream / vanilla kernel check

I tested with a vanilla/upstream kernel and the issue does NOT reproduce there (CachyOS-specific bug)

### Kernel variant

linux-cachyos (EEVDF, Clang)

### System information (cachyos-bugreport.sh)

```text
https://paste.cachyos.org/p/bf15f4e.log
```

### Manual system information (if cachyos-bugreport.sh is unavailable)

```text

```

### Bug description

My Cudy WU650 (Realtek 0bda:c811) USB Wi-Fi adapter is not detected correctly when using the linux-cachyos 7.1.3-2 kernel.

The device is detected by lsusb, but no wireless interface is created, and NetworkManager does not show any Wi-Fi device.

I tested the adapter with:

linux-cachyos 7.1.3-2: Wi-Fi does not work.
linux-cachyos-lts 6.18.38-2: Wi-Fi works, although the connection is unstable.
Lubuntu (kernel 7.0.0-27-generic): Wi-Fi works correctly.

I also tried the rtl8821cu-morrownr-dkms-git driver. It fails to build on the 7.1.3-2 kernel due to kernel API changes, but it builds and works on the LTS kernel.

This appears to be a regression affecting the Realtek 0bda:c811 chipset on the linux-cachyos 7.1 kernel.

### Steps to reproduce

1_Install CachyOS with the linux-cachyos 7.1.3-2 kernel.
2_Connect a Cudy WU650 USB Wi-Fi adapter (Realtek 0bda:c811).
3_Boot the system.
4_Check ip link or NetworkManager.
5_No wireless interface is created, although lsusb detects the USB device.

### Expected behavior

The Wi-Fi adapter should be detected automatically, a wireless interface should be created, and available Wi-Fi networks should appear in NetworkManager, just like they do on linux-cachyos-lts 6.18 and Lubuntu (kernel 7.0.0-27-generic).

### Actual behavior

The USB adapter is detected by lsusb (Realtek 0bda:c811), but no wireless interface is created. ip link only shows the Ethernet interfaces, and NetworkManager does not detect any Wi-Fi device. Loading the rtl8xxxu module does not help. The rtl8821cu-morrownr-dkms-git driver also fails to build on the linux-cachyos 7.1.3-2 kernel, while it builds and works on the LTS kernel.

### Logs / stack traces

```text
[    4.069746] usb 1-9: new high-speed USB device number 4 using xhci_hcd
[    4.276782] usb 1-9: New USB device found, idVendor=0bda, idProduct=c811, bcdDevice=2.00
[    4.276789] usb 1-9: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    4.276792] usb 1-9: Product: 802.11ac NIC
[    4.276794] usb 1-9: Manufacturer: Realtek
[    4.276796] usb 1-9: SerialNumber: 123456

The USB device is detected correctly by the kernel, but no wireless interface (wlan*) is created and NetworkManager does not detect any Wi-Fi device.
```

### Additional system information

System information:

- Distribution: CachyOS (Arch Linux)
- Kernel: 7.1.3-2-cachyos
- Desktop Environment: KDE Plasma 6.7.2 (Wayland)
- Init system: systemd 261
- CPU: AMD Ryzen 5 8500G
- GPU: AMD Radeon 740M (amdgpu)
- RAM: 16 GB
- Motherboard: Gigabyte A620M H (UEFI F31)
- Wi-Fi adapter: Cudy AC650 (Realtek USB, ID 0bda:c811)
- Driver tested: rtl8821cu-morrownr-dkms-git 5.12.0.4.210.7f63a9d-1
- Ethernet: Realtek RTL8111/8168 (r8169)

Additional notes:

- The adapter is detected by lsusb as Realtek 0bda:c811.
- On kernel 7.1.3-2-cachyos, the DKMS driver (rtl8821cu-morrownr-dkms-git) fails to build because of kernel API changes, with errors such as:
  - no member named 'tag' in 'struct pppoe_hdr'
  - no member named 'tag_data' in 'struct pppoe_tag'
- Because the module cannot be built, no Wi-Fi driver is loaded and no wireless interface is created.
- The same adapter works with CachyOS LTS (Linux 6.18.x), although performance is limited.
- The adapter also works correctly on Lubuntu using kernel 7.0.0-27-generic.

**Comment by 1Naim** [comment]
can u check if `rtw88_8821cu` is loaded?

**Comment by Benicio54** [comment]
I checked it.

The built-in module `rtw88_8821cu` is present and can be loaded manually with:

sudo modprobe rtw88_8821cu

After loading it:

- `wlan0` is created.
- `iw dev` detects the interface.
- `nmcli device` shows `wlan0` as a Wi-Fi device.
- `nmcli device wifi list` successfully scans and lists nearby access points.

However, the driver is not working correctly.

When I try to connect to any Wi-Fi network (both my router and my phone hotspot), the authentication starts but never completes.

The kernel log only shows repeated authentication attempts, for example:

wlan0: authenticate with xx:xx:xx:xx:xx:xx
wlan0: send auth (try 1/3)
wlan0: authenticated

After that, nothing else happens. NetworkManager eventually goes back to scanning, and the desktop becomes unstable or freezes while trying to connect.

So the interface exists and scanning works, but association/authentication never completes.

I also tested with my phone hotspot to rule out a router configuration issue, but the result is the same.

**Comment by simiscoool-afk** [comment]
issue should be resolved now, can you test on latest kernel?
